version: "3.5"
services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: big-data-lab-namenode
    volumes:
      - ./workspace/hdfs/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=big-data-lab
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
    networks:
      big-data-lab-net:
        ipv4_address: 172.27.1.5

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: big-data-lab-datanode
    volumes:
      - ./workspace/hdfs/datanode:/hadoop/dfs/data
      - ./bank:/bank
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    depends_on:
      - namenode
    ports:
      - "50075:50075"
    networks:
      big-data-lab-net:
        ipv4_address: 172.27.1.6

  hive-server:
    image: bde2020/hive:2.3.2
    container_name: big-data-lab-hive-server
    env_file:
      - ./hadoop-hive.env
    ports:
      - "10000:10000"
    networks:
      big-data-lab-net:
        ipv4_address: 172.27.1.7

  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: big-data-lab-spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    env_file:
      - ./hadoop-hive.env
    networks:
      big-data-lab-net:
        ipv4_address: 172.27.1.10

  spark-worker:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: big-data-lab-spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore
    ports:
      - 8081:8081
    env_file:
      - ./hadoop-hive.env
    networks:
      big-data-lab-net:
        ipv4_address: 172.27.1.11

  zeppelin:
    image: openkbs/docker-spark-bde2020-zeppelin
    hostname: zeppelin
    container_name: big-data-lab-zeppelin
    environment:
      CORE_CONF_fs_defaultFS: "hdfs://namenode:8020"
      SPARK_MASTER: "spark://spark-master:7077"
      MASTER: "spark://spark-master:7077"
      SPARK_MASTER_URL: spark://spark-master:7077
      ZEPPELIN_PORT: 8080
      ZEPPELIN_JAVA_OPTS:
        -Dspark.driver.memory=1g
        -Dspark.executor.memory=2g
    ports:
      - 19090:8080
    env_file:
      - ./hadoop-hive.env
    volumes:
      - ./workspace/zeppelin/data:/usr/lib/zeppelin/data:rw
      - ./workspace/zeppelin/notebook:/usr/lib/zeppelin/notebook:rw
    command: /usr/lib/zeppelin/bin/zeppelin.sh
    networks:
      big-data-lab-net:
        ipv4_address: 172.27.1.12

  hue:
    image: gethue/hue:20191107-135001
    hostname: hue
    container_name: big-data-lab-hue
    dns: 8.8.8.8
    ports:
      - "8888:8888"
    volumes:
      - ./hue-overrides.ini:/usr/share/hue/desktop/conf/z-hue.ini
    depends_on:
      - "database"
    networks:
      big-data-lab-net:
        ipv4_address: 172.27.1.13

  database:
    image: mysql:5.7
    hostname: database
    container_name: big-data-lab-mysql
    ports:
      - "33061:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./workspace/mysql/data:/var/lib/mysql
      - ./workspace/mysql/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hue
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    networks:
      big-data-lab-net:
        ipv4_address: 172.27.1.14

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zookeeper
    container_name: big-data-lab-zookeeper
    ports:
      - "2181:2181"
    networks:
      big-data-lab-net:
        ipv4_address: 172.27.1.15

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    hostname: kafka
    container_name: big-data-lab-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.27.1.16
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      big-data-lab-net:
        ipv4_address: 172.27.1.16

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    hostname: elasticsearch
    container_name: big-data-lab-elasticsearch
    volumes:
      - ./ws/elasticsearch/logs:/usr/share/elasticsearch/logs/
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      big-data-lab-net:
        ipv4_address: 172.27.1.18

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    hostname: kibana
    container_name: big-data-lab-kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    networks:
      big-data-lab-net:
        ipv4_address: 172.27.1.19
    depends_on:
      - elasticsearch


networks:
  big-data-lab-net:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
